Artist.create(name: "Michael Jackson", age: rand(50), title: "King of Pop", instrument_id: Instrument.first)
Artist.create(name: "Stevie Wonder", age: rand(50), title: "Little Stevie Wonder", instrument_id: Instrument.first)
Artist.create(name: "Elvis Presley", age: rand(50), title: "the King", instrument_id: Instrument.second)
Artist.create(name: "Whitney Houston", age: rand(50), title: "The Voice", instrument_id: Instrument.third)
Artist.create(name: "Beyoncé", age: rand(50), title: "Destiny's Child", instrument_id: Instrument.second)

Instrument.create(name: "Guitar", classification: "Strings", artist_id: Artist.third)
Instrument.create(name: "Violin", classification: "Strings", artist_id: Artist.second)
Instrument.create(name: "Flute", classification: "Woodwind", artist_id: Artist.first)
Instrument.create(name: "Xylophone", classification: "Percussion", artist_id: Artist.second)
