Artist.create(name: "Michael Jackson", age: rand(50), title: "King of Pop")
Artist.create(name: "Stevie Wonder", age: rand(50), title: "Little Stevie Wonder")
Artist.create(name: "Elvis Presley", age: rand(50), title: "the King")
Artist.create(name: "Whitney Houston", age: rand(50), title: "The Voice")
Artist.create(name: "Beyoncé", age: rand(50), title: "Destiny's Child")

Instrument.create(name: "Guitar", classification: "Strings")
Instrument.create(name: "Violin", classification: "Strings")
Instrument.create(name: "Flute", classification: "Woodwind")
Instrument.create(name: "Xylophone", classification: "Percussion")

Post.create(artist_id: Artist.first, instrument_id: Instrument.second)
Post.create(artist_id: Artist.second, instrument_id: Instrument.third)
Post.create(artist_id: Artist.third, instrument_id: Instrument.fourth)
Post.create(artist_id: Artist.fourth, instrument_id: Instrument.first)